// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDJ-lvnxcEDfa1caiAtPAo2nhKSFYV-A',
    appId: '1:651359027212:web:4ed97e155fa4925f9d2e29',
    messagingSenderId: '651359027212',
    projectId: 'classroom-92c5d',
    authDomain: 'classroom-92c5d.firebaseapp.com',
    storageBucket: 'classroom-92c5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aCYDjAQFhNHR52rD7XGn7VkAgZQflVo',
    appId: '1:651359027212:android:f2a4cbb99180cf0d9d2e29',
    messagingSenderId: '651359027212',
    projectId: 'classroom-92c5d',
    storageBucket: 'classroom-92c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuf0kCpQ1aHyVmWGpRmRUyj87IfmqjCNI',
    appId: '1:651359027212:ios:1526ba49e975b0399d2e29',
    messagingSenderId: '651359027212',
    projectId: 'classroom-92c5d',
    storageBucket: 'classroom-92c5d.appspot.com',
    iosClientId: '651359027212-3akgfblv75qstavt1jees9h7t1ri50e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.classApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuf0kCpQ1aHyVmWGpRmRUyj87IfmqjCNI',
    appId: '1:651359027212:ios:1526ba49e975b0399d2e29',
    messagingSenderId: '651359027212',
    projectId: 'classroom-92c5d',
    storageBucket: 'classroom-92c5d.appspot.com',
    iosClientId: '651359027212-3akgfblv75qstavt1jees9h7t1ri50e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.classApp',
  );
}
